name: rush_for_villains
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_local_notifications: ^19.5.0
  pedometer: ^4.2.0
  permission_handler: ^13.0.1
  shared_preferences: ^2.5.3
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/Start/
    - lib/All_Assets/coins/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Archer/Archer/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Armored Axeman/Armored Axeman/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Armored Orc/Armored Orc/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Armored Skeleton/Armored Skeleton/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Elite Orc/Elite Orc/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Greatsword Skeleton/Greatsword Skeleton/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Knight/Knight/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Knight Templar/Knight Templar/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Orc/Orc/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Priest/Priest/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Skeleton/Skeleton/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Skeleton Archer/Skeleton Archer/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Slime/Slime/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Soldier/Soldier/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Swordsman/Swordsman/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Werebear/Werebear/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Werewolf/Werewolf/
    - lib/All_Assets/Avatars/Classes/Characters(100x100 split)/Wizard/Wizard/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Black Knight_A/Black Knight_A/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Black Knight_B/Black Knight_B/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Black Knight_C/Black Knight_C/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Blood Monster_A/Blood Monster_A/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Blood Monster_B/Blood Monster_B/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Demoness_A/Demoness_A/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Demoness_B/Demoness_B/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Demon_A/Demon_A/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Demon_B/Demon_B/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Demon_C/Demon_C/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Demon_D/Demon_D/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Demon_E/Demon_E/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Eyeball Monster/Eyeball Monster/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Flame Golem/Flame Golem/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Ghostfire/Ghostfire/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Hellbat/Hellbat/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Hellhound/Hellhound/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Lava Slime/Lava Slime/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Minotaur/Minotaur/
    - lib/All_Assets/Enemies/Characters(100x100 split)/Warlock/Warlock/
    - lib/Backgrounds/
    - lib/ChanceWheel/
    - lib/SoundEffects/
    - lib/Tutorial_Guy/Mavili/
    - lib/Tutorial_Guy/Pinky/
    - lib/Tutorial_Guy/Kupkuzu/
    - lib/Items/arch/
    - lib/Items/axes_halberds/
    - lib/Items/maces_hammers/
    - lib/Items/magic/
    - lib/Items/ranged_other/
    - lib/Items/scythes/
    - lib/Items/shields/
    - lib/Items/spears/
    - lib/Items/special_other/
    - lib/Items/swords/
    - lib/Rewards/Unsorted/
    - lib/Rewards/Armor/Belts/
    - lib/Rewards/Armor/Boots/
    - lib/Rewards/Armor/Chestplates/
    - lib/Rewards/Armor/Gloves/
    - lib/Rewards/Armor/Helmets/
    - lib/Rewards/Armor/Leggings/
    - lib/Rewards/Consumables/Food/
    - lib/Rewards/Handheld_Items/Hoes/
    - lib/Rewards/Handheld_Items/Maces/
    - lib/Rewards/Handheld_Items/Pickaxes/
    - lib/Rewards/Handheld_Items/Scythes/
    - lib/Rewards/Handheld_Items/Shovels/
    - lib/Rewards/Handheld_Items/Spears/
    - lib/Rewards/Handheld_Items/Swords/
    - lib/Rewards/Handheld_Items/Warhammers/
    - lib/Rewards/Materials_Items/Books/
    - lib/Rewards/Materials_Items/Crystals/
    - lib/Rewards/Materials_Items/Dust/
    - lib/Rewards/Materials_Items/Electronics_Mechanics/
    - lib/Rewards/Materials_Items/Fish_Fishing/
    - lib/Rewards/Materials_Items/Ingots/
    - lib/Rewards/Materials_Items/Keys/
    - lib/Rewards/Materials_Items/Kitchen/
    - lib/Rewards/Materials_Items/Musical_Instruments/
    - lib/Rewards/Materials_Items/Plants_Flowers/
    - lib/Rewards/Materials_Items/Tribal_Ritual/
    - lib/Rewards/Mob_Drops/Eyes/
    - lib/Rewards/Mob_Drops/Feathers/
    - lib/Rewards/Mob_Drops/Other_Drops/
    - lib/Rewards/Special_Events/Christmas/
