name: rush_for_villains
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.3
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/Characters/Archer/
    - lib/Characters/DarkMagic/
    - lib/Characters/Faith/
    - lib/Characters/Magic/
    - lib/Characters/Nature/
    - lib/Characters/Paladin/
    - lib/Characters/SwordMan/
    - lib/Characters/Thief/
    - lib/Enemies/Gergin Asker/
    - lib/Enemies/Tekinsiz Canavar!/
    - lib/Enemies/Blood_Monster_A_GIFs/
    - lib/Enemies/Demon_A_GIFs/
